wmsServiceClass: lsst.ctrl.bps.parsl.ParslService

computeSite: slurm
site:
  slurm:
    class: lsst.ctrl.bps.parsl.sites.Slurm
    nodes: 1
    cores_per_node: 20
    mem_per_node: 200
    walltime: "48:00:00"
